### ISSUE TITLE
Noise generator could be more efficient

### ISSUE THREAD

**Issue by akx** [zorggish/FractalCryptGUI#2]
The noise generator is calling `QRandomGenerator::generate()` in a loop.
https://github.com/zorggish/FractalCryptGUI/blob/36b926c7cc68ef688e46348d3d41b1dd3d82816e/core/noizecreator.hpp#L36-L37

It should probably use [`QRandomGenerator::fillRange()`](https://doc.qt.io/qt-5/qrandomgenerator.html#fillRange).

**Comment by zorggomat** [comment]
Unfortunately, QRandomGenerator::fillRange has requirement sizeof(typename) >= sizeof(unsigned int)

**Comment by akx** [comment]
The buffer size 4096 is divisible with common sizes of `unsigned int`...

**Comment by zorggomat** [comment]
Fixed in commit 05c42e7
